module.exports = [
  { name: 'cups01',
    reversed: false,
    location: "",
  },
  { name: 'cups02',
    reversed: false,
    location: "",
  },
  { name: 'cups03',
    reversed: false,
    location: "",
  },
  { name: 'cups04',
    reversed: false,
    location: "",
  },
  { name: 'cups05',
    reversed: false,
    location: "",
  },
  { name: 'cups06',
    reversed: false,
    location: "",
  },
  { name: 'cups07',
    reversed: false,
    location: "",
  },
  { name: 'cups08',
    reversed: false,
    location: "",
  },
  { name: 'cups08',
    reversed: false,
    location: "",
  },
  { name: 'cups10',
    reversed: false,
    location: "",
  }
]
