module.exports = [
  { name: 'cups01',
    reversed: false,
    // image: "./components/images/cups01.jpg",
  },
  { name: 'cups02',
    reversed: false,
    // image: "./components/images/cups02.jpg",
  },
  { name: 'cups03',
    reversed: false,
    // image: "./components/images/cups03.jpg",
  },
  { name: 'cups04',
    reversed: false,
    // image: "./components/images/cups04.jpg",
  },
  { name: 'cups05',
    reversed: false,
    // image: "./components/images/cups05.jpg",
  },
  { name: 'cups06',
    reversed: false,
    // image: "./components/images/cups06.jpg",
  },
  { name: 'cups07',
    reversed: false,
    // image: "./components/images/cups07.jpg",
  },
  { name: 'cups08',
    reversed: false,
    // image: "./components/images/cups08.jpg",
  },
  { name: 'cups09',
    reversed: false,
    // image: "./components/images/cups09.jpg",
  },
  { name: 'cups10',
    reversed: false,
    // image: "./components/images/cups10.jpg",
  }
]
